/**
 * KB pipeline retry / stuck-recovery limits — defined in `src/lib/global.constants.ts`.
 * Re-exported here so existing imports keep working.
 */
export {
  EXTRACT_JOB_MAX_AUTO_RETRIES,
  EXTRACT_JOB_MAX_STUCK_RECOVERIES,
  EXTRACT_JOB_RETRY_BACKOFF_BASE_MS,
  INGESTION_STUCK_TIMEOUT_MINUTES,
  KNOWLEDGE_MANUAL_RETRY_MAX_PER_ITEM,
  KNOWLEDGE_MANUAL_RETRY_MIN_INTERVAL_MS,
  KNOWLEDGE_TRAIN_QUEUE_RATE_LIMIT_MAX_PER_WINDOW,
  KNOWLEDGE_TRAIN_QUEUE_RATE_LIMIT_WINDOW_MS,
  KNOWLEDGE_TRAINING_MAX_STUCK_RECOVERIES,
  KNOWLEDGE_TRAINING_STUCK_TIMEOUT_MINUTES,
  STUCK_RECOVERY_LIMIT_JOB_ERROR,
  TABLE_IMPORT_MAX_STUCK_RECOVERIES,
  TABLE_IMPORT_STUCK_TIMEOUT_MINUTES,
} from '../lib/global.constants';
