import type { LucideIcon } from "lucide-react";
import {
  Bell,
  BookOpen,
  Bookmark,
  Briefcase,
  Building2,
  Calendar,
  Camera,
  ClipboardList,
  Clock,
  CreditCard,
  Download,
  ExternalLink,
  FileText,
  Globe,
  Headphones,
  Heart,
  HelpCircle,
  Home,
  Image,
  Info,
  LifeBuoy,
  Lightbulb,
  Link2,
  Lock,
  Mail,
  MapPin,
  Megaphone,
  MessageCircle,
  Newspaper,
  Package,
  Phone,
  PlayCircle,
  Search,
  Send,
  Settings,
  Share2,
  Shield,
  ShoppingCart,
  Smartphone,
  Star,
  Store,
  Ticket,
  Truck,
  User,
  Users,
  Video,
  Wrench,
  Zap,
} from "lucide-react";

/**
 * Curated quick-link icons (header menu). Keep in sync with
 * `ai-platform-backend/src/user/quick-link-icon-ids.ts` → `QUICK_LINK_ICON_IDS`.
 */
export const QUICK_LINK_ICON_IDS = [
  "external-link",
  "home",
  "mail",
  "phone",
  "message-circle",
  "help-circle",
  "file-text",
  "link-2",
  "calendar",
  "shopping-cart",
  "credit-card",
  "user",
  "users",
  "building-2",
  "map-pin",
  "globe",
  "package",
  "truck",
  "book-open",
  "life-buoy",
  "wrench",
  "search",
  "settings",
  "shield",
  "bell",
  "bookmark",
  "briefcase",
  "camera",
  "clipboard-list",
  "clock",
  "download",
  "headphones",
  "heart",
  "image",
  "info",
  "lightbulb",
  "lock",
  "megaphone",
  "newspaper",
  "play-circle",
  "send",
  "share-2",
  "smartphone",
  "star",
  "store",
  "ticket",
  "video",
  "zap",
] as const;

export type QuickLinkIconId = (typeof QUICK_LINK_ICON_IDS)[number];

const QUICK_LINK_ICONS: Record<QuickLinkIconId, LucideIcon> = {
  "external-link": ExternalLink,
  home: Home,
  mail: Mail,
  phone: Phone,
  "message-circle": MessageCircle,
  "help-circle": HelpCircle,
  "file-text": FileText,
  "link-2": Link2,
  calendar: Calendar,
  "shopping-cart": ShoppingCart,
  "credit-card": CreditCard,
  user: User,
  users: Users,
  "building-2": Building2,
  "map-pin": MapPin,
  globe: Globe,
  package: Package,
  truck: Truck,
  "book-open": BookOpen,
  "life-buoy": LifeBuoy,
  wrench: Wrench,
  search: Search,
  settings: Settings,
  shield: Shield,
  bell: Bell,
  bookmark: Bookmark,
  briefcase: Briefcase,
  camera: Camera,
  "clipboard-list": ClipboardList,
  clock: Clock,
  download: Download,
  headphones: Headphones,
  heart: Heart,
  image: Image,
  info: Info,
  lightbulb: Lightbulb,
  lock: Lock,
  megaphone: Megaphone,
  newspaper: Newspaper,
  "play-circle": PlayCircle,
  send: Send,
  "share-2": Share2,
  smartphone: Smartphone,
  star: Star,
  store: Store,
  ticket: Ticket,
  video: Video,
  zap: Zap,
};

/** Resolve a stored id to a Lucide icon; unknown/missing → external-link */
export function getQuickLinkIcon(id: string | undefined): LucideIcon {
  if (!id) return ExternalLink;
  return QUICK_LINK_ICONS[id as QuickLinkIconId] ?? ExternalLink;
}

export function isQuickLinkIconId(id: string): id is QuickLinkIconId {
  return (QUICK_LINK_ICON_IDS as readonly string[]).includes(id);
}
