/**
 * Curated quick-link icon ids (header menu). Keep in sync with
 * `chat-widget/src/lib/quickLinkIcons.ts` → `QUICK_LINK_ICON_IDS`.
 */
export const QUICK_LINK_ICON_IDS = [
  'external-link',
  'home',
  'mail',
  'phone',
  'message-circle',
  'help-circle',
  'file-text',
  'link-2',
  'calendar',
  'shopping-cart',
  'credit-card',
  'user',
  'users',
  'building-2',
  'map-pin',
  'globe',
  'package',
  'truck',
  'book-open',
  'life-buoy',
  'wrench',
  'search',
  'settings',
  'shield',
  'bell',
  'bookmark',
  'briefcase',
  'camera',
  'clipboard-list',
  'clock',
  'download',
  'headphones',
  'heart',
  'image',
  'info',
  'lightbulb',
  'lock',
  'megaphone',
  'newspaper',
  'play-circle',
  'send',
  'share-2',
  'smartphone',
  'star',
  'store',
  'ticket',
  'video',
  'zap',
] as const;

export type QuickLinkIconId = (typeof QUICK_LINK_ICON_IDS)[number];
