import type { WorkspaceBillingSummary } from "@/types/billing";

/** Static catalog aligned with product plan definitions (UI-only; no API). */
export const LANDING_PLANS_BILLING_SUMMARY: WorkspaceBillingSummary = {
  plan: { key: "free" },
  entitlements: { isTrialPlan: true, addonsAllowed: false },
  planCatalog: [
    {
      key: "free",
      name: "Free",
      priceMonthly: 0,
      botLimit: 1,
      memberLimit: 1,
      monthlyAiCredits: 50,
      kbStorageMbPerBot: 5,
      analyticsHistoryDays: 7,
      canExportReports: false,
      checkoutAvailable: false,
    },
    {
      key: "starter",
      name: "Starter",
      priceMonthly: 49,
      botLimit: 1,
      memberLimit: 5,
      monthlyAiCredits: 500,
      kbStorageMbPerBot: 15,
      analyticsHistoryDays: null,
      canExportReports: true,
      checkoutAvailable: true,
    },
    {
      key: "pro",
      name: "Pro",
      priceMonthly: 99,
      botLimit: 1,
      memberLimit: 10,
      monthlyAiCredits: 2000,
      kbStorageMbPerBot: 25,
      analyticsHistoryDays: null,
      canExportReports: true,
      checkoutAvailable: true,
    },
  ],
  addonCatalog: [
    {
      key: "ai_credits_1000",
      name: "1,000 extra AI credits",
      billingInterval: "one_time",
      priceUsd: 30,
      scope: "workspace",
      checkoutAvailable: true,
    },
    {
      key: "extra_bot",
      name: "Extra bot",
      billingInterval: "monthly",
      priceUsd: 49,
      scope: "workspace",
      checkoutAvailable: true,
    },
    {
      key: "remove_branding",
      name: "Remove Powered by Assistrio",
      billingInterval: "monthly",
      priceUsd: 20,
      scope: "workspace",
      checkoutAvailable: true,
    },
    {
      key: "kb_storage_5mb",
      name: "+5 MB KB storage",
      billingInterval: "monthly",
      priceUsd: 10,
      scope: "bot",
      checkoutAvailable: true,
    },
    {
      key: "kb_storage_10mb",
      name: "+10 MB KB storage",
      billingInterval: "monthly",
      priceUsd: 15,
      scope: "bot",
      checkoutAvailable: true,
    },
  ],
};
