/**
 * Main topic taxonomy (analytics / classification). ~30 mains + `other` fallback.
 * Sub-topics are scoped per main in {@link MAIN_TOPIC_SUBTOPICS}.
 *
 * Note: `availability` was omitted as a main topic to keep the main list at 30 keys
 * (per product spec); drill-down for stock/availability lives under `order_status`,
 * `shipping_delivery`, `returns_exchange`, and related mains.
 */

export const TOPIC_TAXONOMY_IDS = [
  'pricing',
  'billing',
  'subscription',
  'refund',
  'product_question',
  'technical_support',
  'bug_report',
  'account_access',
  'setup_onboarding',
  'integration',
  'api_webhook',
  'sales',
  'demo_request',
  'human_agent',
  'lead_capture',
  'order_status',
  'shipping_delivery',
  'returns_exchange',
  'appointment_booking',
  'documentation',
  'feature_request',
  'complaint',
  'feedback',
  'security_privacy',
  'compliance',
  'cancellation',
  'trial',
  'usage_limits',
  'general_question',
  'other',
] as const;

export type TopicTaxonomyId = (typeof TOPIC_TAXONOMY_IDS)[number];

export const TOPIC_LABELS: Record<TopicTaxonomyId, string> = {
  pricing: 'Pricing',
  billing: 'Billing',
  subscription: 'Subscription',
  refund: 'Refund',
  product_question: 'Product question',
  technical_support: 'Technical support',
  bug_report: 'Bug report',
  account_access: 'Account access',
  setup_onboarding: 'Setup & onboarding',
  integration: 'Integration',
  api_webhook: 'API & webhooks',
  sales: 'Sales',
  demo_request: 'Demo request',
  human_agent: 'Human agent',
  lead_capture: 'Lead capture',
  order_status: 'Order status',
  shipping_delivery: 'Shipping & delivery',
  returns_exchange: 'Returns & exchange',
  appointment_booking: 'Appointment booking',
  documentation: 'Documentation',
  feature_request: 'Feature request',
  complaint: 'Complaint',
  feedback: 'Feedback',
  security_privacy: 'Security & privacy',
  compliance: 'Compliance',
  cancellation: 'Cancellation',
  trial: 'Trial',
  usage_limits: 'Usage limits',
  general_question: 'General question',
  other: 'Other',
};

/** Allowed sub-topic ids per main topic (snake_case). */
export const MAIN_TOPIC_SUBTOPICS: Record<TopicTaxonomyId, readonly string[]> = {
  pricing: ['plan_price', 'discount', 'custom_quote', 'comparison', 'free_plan'],
  billing: ['failed_payment', 'invoice', 'payment_method', 'tax', 'overcharge'],
  subscription: ['plan_change', 'renewal', 'pause_subscription', 'subscription_status', 'upgrade_downgrade'],
  refund: ['refund_request', 'refund_status', 'refund_policy', 'partial_refund'],
  product_question: ['how_it_works', 'compatibility', 'specs', 'comparison_question', 'usage_question'],
  technical_support: ['not_working', 'error_message', 'troubleshooting', 'performance', 'configuration_issue'],
  bug_report: ['broken_feature', 'visual_bug', 'data_issue', 'crash', 'unexpected_behavior'],
  account_access: ['login_issue', 'password_reset', 'verification', 'permissions', 'account_locked'],
  setup_onboarding: ['first_setup', 'installation', 'configuration', 'onboarding_question', 'setup_help'],
  integration: ['wordpress', 'shopify', 'crm', 'zapier', 'website_embed'],
  api_webhook: ['api_key', 'webhook_setup', 'api_error', 'rate_limit', 'endpoint_question'],
  sales: ['purchase_intent', 'plan_recommendation', 'sales_question', 'enterprise_question', 'contact_sales'],
  demo_request: ['book_demo', 'product_walkthrough', 'trial_demo', 'demo_availability'],
  human_agent: ['talk_to_human', 'support_agent', 'callback_request', 'escalation'],
  lead_capture: ['name', 'email', 'phone', 'company', 'budget', 'lead_callback_request'],
  order_status: ['tracking', 'delivery_status', 'order_update', 'order_issue'],
  shipping_delivery: ['shipping_cost', 'delivery_time', 'delayed_delivery', 'shipping_area'],
  returns_exchange: ['return_request', 'exchange_request', 'return_policy', 'damaged_item'],
  appointment_booking: ['book_appointment', 'reschedule', 'cancel_appointment', 'availability_slot'],
  documentation: ['docs_request', 'tutorial_request', 'guide_question', 'setup_docs'],
  feature_request: ['new_feature', 'improvement_request', 'customization', 'roadmap_question'],
  complaint: ['bad_experience', 'service_issue', 'product_issue', 'unresolved_problem'],
  feedback: ['positive_feedback', 'negative_feedback', 'suggestion', 'review'],
  security_privacy: ['data_privacy', 'security_question', 'gdpr', 'account_security'],
  compliance: ['legal_question', 'policy_question', 'terms_question', 'compliance_docs'],
  cancellation: ['cancel_order', 'cancel_subscription', 'cancellation_policy', 'cancellation_status'],
  trial: ['free_trial', 'trial_limit', 'trial_extension', 'trial_question'],
  usage_limits: ['credit_usage', 'message_limit', 'quota_question', 'usage_tracking', 'limit_explanation'],
  general_question: ['greeting', 'general_help', 'unclear_question', 'small_talk'],
  other: ['other'],
};
