/** User-visible strings for the per-bot Usage dashboard (kept in one module for copy tests). */
export const USAGE_DASHBOARD_COPY = {
  title: 'Usage',
  subtitle: 'Track message credits and usage for this assistant.',
  emptyTitle: 'No usage recorded for this range.',
  emptyHint: 'Usage appears after visitors send messages.',
  billableHint: 'Credits counted toward billing in this range.',
  nonBillableHint: 'Preview or non-billed events. Attachment messages are currently not billable.',
  creditsOverTimeTitle: 'Credits over time',
  creditsOverTimeDescription: 'Total, billable, and non-billable credits by period.',
  messagesOverTimeTitle: 'Message mix over time',
  messagesOverTimeDescription: 'Visitor message shapes counted in usage (stacked).',
  usageTypeTitle: 'Usage by type',
  usageTypeDescription: 'How usage events group by channel or intent.',
  voiceCardTitle: 'Voice & dictation',
  voiceCardDescription: 'Speech input aggregates for the selected range (no recordings).',
  tableTitle: 'Usage summary by type',
  tableDescription: 'Events and credits attributed to each usage category.',
  errorTitle: "We couldn't load usage",
  errorDescription: 'Check your connection and try again. If the problem continues, try a shorter date range.',
} as const;
